# fly.toml app configuration file generated for snowy-sunset-6320 on 2023-09-11T22:28:10-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "snowy-sunset-6320"
primary_region = "ord"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
