# fly.toml app configuration file generated for tom-blog-app-1 on 2023-09-11T14:57:15-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tom-blog-app-1"
primary_region = "ord"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
