GET http://localhost:3000/post

###

GET http://localhost:3000/post/15

###


POST http://localhost:3000/
Content-Type: application/json

{
    "title": "Title test 2",
    "body": "Body test 2",
    "comments": "Comments test 2",
    "publish_status": "false",
}