# GET http://localhost:3000/post

# ###

# GET http://localhost:3000/post/15

# ###


POST http://localhost:3000/post
Content-Type: application/json

{
    "title": "Title test 5",
    "text": "Body test 3",
    "comments": "Comments test 3",
    "publish_status": "false"
}