GET http://localhost:3000/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3Q1IiwiaWF0IjoxNjY2MzA5MzQ0fQ.AqWn4OAXQgaHodqOenziWNHFsDQqyex-LGFaolv0ZrA
###

GET http://localhost:3000/post
###
GET http://localhost:3000/post/634c4f14d0b5311d61235532

###


POST http://localhost:3000/post
Content-Type: application/json

{
    "title": "Title test 1",
    "text": "Body test 1",
    "comments": "Comments test 1",
    "publish_status": "false"
}
###

DELETE http://localhost:3000/post/634c4f14d0b5311d61235532

###

PATCH http://localhost:3000/post/634cbc5c8663cf5eb8e427c7
Content-Type: application/json

{
    "title": "Patch test 1",
    "text": "Patch text 1",
    "comments": "Patch comments 1",
    "publish_status": "Patch publish_status 1"
}

###
//Get all comments
GET http://localhost:3000/comment

###
//Get a specific comment
GET http://localhost:3000/comment/63521488257a4751be19fe9c

###
//Save comment to database
POST http://localhost:3000/comment
Content-Type: application/json

{
    "text": "test1",
    "email": "test@gmail.com"
}

###
//Update an existing comment
PATCH http://localhost:3000/comment/63521488257a4751be19fe9c
Content-Type: application/json

{
    "text": "updated test1",
    "email": "updatedtest@gmail.com"
}

###
//Delete a comment
DELETE http://localhost:3000/comment/63521488257a4751be19fe9c


###
//Save comments to a specific post
POST http://localhost:3000/post/634f31cb4bf85723a546c3f3/comment
Content-Type: application/json

{
    "text": "testx",
    "email": "test2@gmail.com"

    
}


###
# Testing Post + Comments GET in same function

GET http://localhost:3000/post/634f31cb4bf85723a546c3f3

###

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "username": "test5",
    "password": "test5"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "test5",
    "password": "test5"
    
}

###
GET http://localhost:3000/auth/users